language: python
python:
  - 3.7
install:
  - pip install -U pip
  - pip install pipenv
    #  - pipenv install --dev
script:
  - bandit ./*
  - black --check .
  - safety check -r requirements.txt
  - mypy .
